var planetsMetadata = 
         [{
                  name : 'Alderaan',
                  asset : './assets/alderaan_zoom.dae',
                  capital : "Aldera",
                  abstract : "Alderaan, située dans les Mondes Centraux, était la deuxième planète du système Alderaan, et le foyer de nombreux héros, notamment Leia Organa Solo, Bail Organa et Ulic Qel-Droma. Connue intergalactiquement pour sa beauté préservée, sa culture raffinée et son engagement envers la paix, les Alderaaniens travaillaient avec et pour la nature qu'ils souhaitaient protéger du mieux qu'ils pouvaient",
                  history : "Alderaan était un fondateur de la République Galactique en 25 053 BBY et une des ancres pour les premières exploratiosn de l'hyper-espace. Alderaan était le quartier général des Ingénieurs Royaux d'Alderaan, un des meilleurs bataillons de la République; avec ces vaisseaux les colons Alderaniens ont conquis Nim Drovis. Pendant les Guerres Mandaloriennes, la planète était menacée d'invasion par les forces de Cassus Fett, mais la force d'invasion fut toute entière éliminée prématurément par une erreur d'utilisation d'un ancien artefact Sith.",
                  geography : "Considérée comme 'la plus belle Étoile' des Mondes Centraux, des plaines sauvages et de vieilles montagnes domianient la surface de la planète. De larges océans et des mers éparpillées procuraient à la planète des conditions idéales pour qu'une grande variété de faune et de flore se développe. Ainsi, Alderaan hébergeait les aniamux les plsu fameux de la galaxie, tels les nerfs, les grazer et le thranta. Les citées d'Alderaan étaient souvent construites en prenant soin de préserver la nature. Crevasse City par exemple fut ocnstruite sur les murs d'un canyon, quasiment invisible depuis le ciel. D'autres furent cosntruites sur des pilotis le long de la côte ou sous la glace polaire. La capitale, Aldera, renommée pour son université, fut construite sur une petite île au centre d'n cratère volcanique.",
                  society : " La culture d'Alderaan considérait l'éducation, la comédie, les beaux arts et la résolution pacifique des conflits. Leur participation au sénat Galactique leur tenait à cœur et cela se perpétua à l'équivalent de l'Empire. Les Alderaaniens cherchaient constamment une existence en harmonie avec leur environnement, évidente dans l'intégration de leur société au terrain naturel de la planète. Ils étaient aussi connus pour leur philosophie.",
                  government : "En restant une société démocratique, Alderaan était dirigée par une monarchie constitutionelle héréditaire. La Maison d'Organa présidait au dessus de la Cour Suprème et du Haut Conseil législatif d'Alderaan. Ses monarques portaient variablement les titres 'Prince', 'Premier Conseiller', 'Reine', 'Roi' et 'Vice-Roi'. Traditionelleent, l'héritier du trône d'ALderaan siégeait aussi au HAut COnseil d'Alderaan et une période comme Sénateur d'Alderaan. Un vizir aidait le monarque à gouverner, et de nombreuses maisons Nobles avaient chacuen forte influence au gouvernement.",
                  behind : "Grindelwald in Switzerland was scouted for Star Wars: Episode III Revenge of the Sith, to capture plate photography for backdrops on the planet Alderaan."
         },
         {
                  name : 'Naboo',
                  asset : './assets/naboo_zoom.dae',
                  capital : "Theed (Humaine), Otho Gunga (Gungan)",
                  abstract : "Naboo (prononcé /n&#601;'bu/) était une planète du secteur majeur de Chomell, situé près de la Brodure Extérieure. C'étiat un territoire intact composé de large plaines , marécages et mers. C'était notamment la patrie de figures historiques majeures ayant joué d'importants rôles dans la chute de la République et la montée de l'Empire. Notamment Padmé Amidala, Empereur Palpatine et Jar Jar Binks.",
                  geography : " Naboo était un monde géologiquement unique dans la galaxie. Une couche de plasma couvrait le cœur intérieur, que l'on suppose principalement composé d'un alliage de nickel et de Fer, avec des traces d'autres éléments. Ces éléments étaient présents en abondance dans d'autre compositions chimiques de la galaxie, mais les propriétés exceptionelles du plasma attiraient les astrophyisiciens, ce plasma ayant prodigué une énergie propre et efficace aux deux civilisations primaires de la planète.",
                  society : " La culture d'Alderaan considérait l'éducation, la comédie, les beaux arts et la résolution pacifique des conflits. Leur participation au sénat Galactique leur tenait à cœur et cela se perpétua à l'équivalent de l'Empire. Les Alderaaniens cherchaient constamment une existence en harmonie avec leur environnement, évidente dans l'intégration de leur société au terrain naturel de la planète. Ils étaient aussi connus pour leur philosophie.",
                  history : "Aux environs de 3961 BBY, avant la fin de la Guerre Civile des Siths, Elsinoré den Tasia accéda au trône des Modens du Noyau de Grizmallt. Elle sponsorisa l'explorateur de la République Kwilaan, qui découvra Naboo ave cune flotte de trois navires Tasia, Constant et Mère Vima. La planète fût nommée ainsi selon la divinité Nabu. Elle devint rapidement connue des grands chasseurs qui avaient pour cible les veermoks indigènes, bien que ce soit cinq siècles avant la colonisation Humaien permanente.",
                  culture : "Historiquement, les Naboo étaient un peuple nomade , migrant en tribus et en clans sur le vaste 'océan' de prairies, avec peu d'arrêts prolongés. Les tribus déscendaient des vasseaux de la colonie amenée à Naboo, et les clans descendaient des pères fondateurs. Les Naboo avaient toujorus en haute estime la généalogie, bien que durant l'ère de la Reine Amidala peu de familels purent relier leur histoire aux colons originels avec certitude.",
                  government : "Les politiques de Naboo étaient remarquable, applicant un système de monarchie démocratique où l'éligibilité du Monarque de Naboo n'étiat pas lié à l'âge ou au pouvoir; traditionellement les gouvernants étiaent choisis pour leur intelligence. De même, les citoyens n'étaient sujets à aucuen restriction d'âge pour voter, mais devaient effectuer un test d'aptitudes pour prouver un certain niveau de maturité intelectuelle. Les conseillers du monarque étaient aussi élus par le vote. Cependant, les Naboo préféraient la pureté du cœur à n'importe quelle autre qualité ce qui parfois les poussa à éduquer des personnes trop arrangeantes à des positions au delà de leurs capacités.",
                  behind :"The buildings of Naboo are based after a cathedral turned mosque then turned museum, the Hagia Sophia, in Istanbul, Turkey. The real-world locations for Naboo were Plaza de España in Spain, and Lake Como and Caserta Palace in Italy, among others."
         },
         {
                  name : 'Coruscant',
                  asset : './assets/coruscant_zoom.dae',
                  capital : "Galactic City",
                  abstract : "Coruscant, (prononcé /'k&#596;&#633;&#601;s&#593;nt/), originellement appelée Notron, aussi connue comme le Centre Impérial ou la Reine du Noyau, était une planète située au Coeur de la Galaxie. Il était généralement accordé que Coruscant était, durant la majorité de l'histoire galactique, le monde le plus important de la galaxie. À diverses époques, il s'agissait de la capitale de la République Galactique, de l'Empire Galactique, de la Nouvelle République, de l'empire Yuuzhan Vong, de l'Alliance Galactique, brièvement de l'Empire Fel, de l'Empire Galactique de Dark Krayt, et de la Fédération Galactique du Triumvirate. En contrôlant Coruscant, ces gouvernemens contrôlaient la plupart de la galaxie.",
                  geography : " Géologiquement, la planète était composée d'un cœur fondu, entouré d'un manteau de roches et de silicate. À ses pôles se tenainet d'énormes blocs de glace populaire au près des touristes. L'entière surface de Coruscant était couverte de, gonflée par une population de plus de cent milliards à plusieurs trillions, selon l'époque. Après la fin de la Guerre des Clones, une note officielle nota 1 trilliard de résidents permanents officiels. Les statistiques n'incluaient pas les gens de passage, les travailleurs temporaires, la population non recensée, ou encore les habitants des infrastructures orbitales. À cause de ces omissions, la population réelle de Coruscant étaient estimée le triple de la note officielle.",
                  history : "L'Histoire enregistrée de Coruscant remonte à si loin qu'elle est devenue indistinguable de la légende...",
                  society : "Coruscant était le foyer d'une certaine variété d'espèces, bien que les Humaisn en représenatient la majorité. La plupart des espèces natives de la planète étaient soit exteintes soit regroupée dans les parties les plus profondes du Monde Souterrain depuis l'époque de l'Ancienne République. La planète était supposée être le foyer des Humains. Même si tous les citoyens renommés n'éaient nés à Coruscant, beaucoup considéraient cette planète comme leur patrie.",
                  government : "La planet résistait aux changements de bords politiques, procurant une stabilité à travers les rebellions, la longue chute de la corrompue Ancienne République, et l'époustouflant introduction du Nouvel Ordre de l'Empereur."
         },
         {
                  name : "Tatooine",
                  asset : './assets/tatooine_zoom.dae',
                  capital : "Bestine",
                  abstract : "Tattoine (prononcé /tætu'in/; Jawaese: Tah doo Een e) était un monde désertique et la première plan!te de l'histoire du système binaire de Tatoo. Elle faisait partie du secteur Arkanis des Territoires Éloignés, habitée par de pauvres autochtones qui faisaient principalement pousser des moisissures pour survivre.",
                  history : "C'était ici que le Maître Jedi Qui Gon Jin reconnu le potentiel d'Anakin Skywalker à devenir un Jedi, et qu'il l'introduit à Obi-Wan Kenobi, son futur maître et mentor. Tatooine fût aussi le foyer du fils d'Anakin, Luke, qui y vécut jusqu'à devenir un jeune adulte.",
                  geography : "Tatooine est supposée être une des plus vieilles planètes de l'espace connu, composée d'un cœur fondu, entouré d'un manteau de roches et de silicate. Des traces fossiles suggèrent la présence de larges océans à la surface de Tatooine, qui séchés laissèrent derrière eux de nombreuses formations géologiques pré-arides, notaament le Canyon du Mendiant, formé aux alentours de 2 000 000 BBY, alors que Tatooine était lush.",
                  society : "The inhabitants of Tatooine included many different species from many parts of the galaxy, as can be seen in the multiple bars and cantinas in the cities. Most creatures on the planet loved to gamble on nearly everything, especially podracing, though the sport declined after the rise of the Empire",
                  government : "Le gouvernement de Tatooine est corrompu et très mal famé, mais cela convient à la population variée et penchant entre paysans, sauvages et bandits."
         },
         {
                  name : "Korriban",
                  asset : './assets/korriban_zoom.dae',
                  capital : "Dresdahe",
                  abstract : "Coruscant, (prononcé /'k&#596;&#633;&#601;s&#593;nt/), originellement appelée Notron, aussi connue comme le Centre Impérial ou la Reine du Noyau, était une planète située au Coeur de la Galaxie. Il était généralement accordé que Coruscant était, durant la majorité de l'histoire galactique, le monde le plus important de la galaxie. À diverses époques, il s'agissait de la capitale de la République Galactique, de l'Empire Galactique, de la Nouvelle République, de l'empire Yuuzhan Vong, de l'Alliance Galactique, brièvement de l'Empire Fel, de l'Empire Galactique de Dark Krayt, et de la Fédération Galactique du Triumvirate. En contrôlant Coruscant, ces gouvernemens contrôlaient la plupart de la galaxie.",
                  geography : " Géologiquement, la planète était composée d'un cœur fondu, entouré d'un manteau de roches et de silicate. À ses pôles se tenainet d'énormes blocs de glace populaire au près des touristes. L'entière surface de Coruscant était couverte de, gonflée par une population de plus de cent milliards à plusieurs trillions, selon l'époque. Après la fin de la Guerre des Clones, une note officielle nota 1 trilliard de résidents permanents officiels. Les statistiques n'incluaient pas les gens de passage, les travailleurs temporaires, la population non recensée, ou encore les habitants des infrastructures orbitales. À cause de ces omissions, la population réelle de Coruscant étaient estimée le triple de la note officielle.",
                  history : "L'Histoire enregistrée de Coruscant remonte à si loin qu'elle est devenue indistinguable de la légende...",
                  society : "Coruscant était le foyer d'une certaine variété d'espèces, bien que les Humaisn en représenatient la majorité. La plupart des espèces natives de la planète étaient soit exteintes soit regroupée dans les parties les plus profondes du Monde Souterrain depuis l'époque de l'Ancienne République. La planète était supposée être le foyer des Humains. Même si tous les citoyens renommés n'éaient nés à Coruscant, beaucoup considéraient cette planète comme leur patrie.",
                  government : "La planet résistait aux changements de bords politiques, procurant une stabilité à travers les rebellions, la longue chute de la corrompue Ancienne République, et l'époustouflant introduction du Nouvel Ordre de l'Empereur."

         },
         {
                  name : "Kamino",
                  asset : './assets/kamino_zoom.dae',
                  capital : "Tipoca",
                  abstract : "Coruscant, (prononcé /'k&#596;&#633;&#601;s&#593;nt/), originellement appelée Notron, aussi connue comme le Centre Impérial ou la Reine du Noyau, était une planète située au Coeur de la Galaxie. Il était généralement accordé que Coruscant était, durant la majorité de l'histoire galactique, le monde le plus important de la galaxie. À diverses époques, il s'agissait de la capitale de la République Galactique, de l'Empire Galactique, de la Nouvelle République, de l'empire Yuuzhan Vong, de l'Alliance Galactique, brièvement de l'Empire Fel, de l'Empire Galactique de Dark Krayt, et de la Fédération Galactique du Triumvirate. En contrôlant Coruscant, ces gouvernemens contrôlaient la plupart de la galaxie.",
                  geography : " Géologiquement, la planète était composée d'un cœur fondu, entouré d'un manteau de roches et de silicate. À ses pôles se tenainet d'énormes blocs de glace populaire au près des touristes. L'entière surface de Coruscant était couverte de, gonflée par une population de plus de cent milliards à plusieurs trillions, selon l'époque. Après la fin de la Guerre des Clones, une note officielle nota 1 trilliard de résidents permanents officiels. Les statistiques n'incluaient pas les gens de passage, les travailleurs temporaires, la population non recensée, ou encore les habitants des infrastructures orbitales. À cause de ces omissions, la population réelle de Coruscant étaient estimée le triple de la note officielle.",
                  history : "L'Histoire enregistrée de Coruscant remonte à si loin qu'elle est devenue indistinguable de la légende...",
                  society : "Coruscant était le foyer d'une certaine variété d'espèces, bien que les Humaisn en représenatient la majorité. La plupart des espèces natives de la planète étaient soit exteintes soit regroupée dans les parties les plus profondes du Monde Souterrain depuis l'époque de l'Ancienne République. La planète était supposée être le foyer des Humains. Même si tous les citoyens renommés n'éaient nés à Coruscant, beaucoup considéraient cette planète comme leur patrie.",
                  government : "La planet résistait aux changements de bords politiques, procurant une stabilité à travers les rebellions, la longue chute de la corrompue Ancienne République, et l'époustouflant introduction du Nouvel Ordre de l'Empereur."

         },
         {
                  name : "Dagobah",
                  asset : './assets/alderaan_zoom.dae',
                  capital : "",
                  abstract : "Coruscant, (prononcé /'k&#596;&#633;&#601;s&#593;nt/), originellement appelée Notron, aussi connue comme le Centre Impérial ou la Reine du Noyau, était une planète située au Coeur de la Galaxie. Il était généralement accordé que Coruscant était, durant la majorité de l'histoire galactique, le monde le plus important de la galaxie. À diverses époques, il s'agissait de la capitale de la République Galactique, de l'Empire Galactique, de la Nouvelle République, de l'empire Yuuzhan Vong, de l'Alliance Galactique, brièvement de l'Empire Fel, de l'Empire Galactique de Dark Krayt, et de la Fédération Galactique du Triumvirate. En contrôlant Coruscant, ces gouvernemens contrôlaient la plupart de la galaxie.",
                  geography : " Géologiquement, la planète était composée d'un cœur fondu, entouré d'un manteau de roches et de silicate. À ses pôles se tenainet d'énormes blocs de glace populaire au près des touristes. L'entière surface de Coruscant était couverte de, gonflée par une population de plus de cent milliards à plusieurs trillions, selon l'époque. Après la fin de la Guerre des Clones, une note officielle nota 1 trilliard de résidents permanents officiels. Les statistiques n'incluaient pas les gens de passage, les travailleurs temporaires, la population non recensée, ou encore les habitants des infrastructures orbitales. À cause de ces omissions, la population réelle de Coruscant étaient estimée le triple de la note officielle.",
                  history : "L'Histoire enregistrée de Coruscant remonte à si loin qu'elle est devenue indistinguable de la légende...",
                  society : "Coruscant était le foyer d'une certaine variété d'espèces, bien que les Humaisn en représenatient la majorité. La plupart des espèces natives de la planète étaient soit exteintes soit regroupée dans les parties les plus profondes du Monde Souterrain depuis l'époque de l'Ancienne République. La planète était supposée être le foyer des Humains. Même si tous les citoyens renommés n'éaient nés à Coruscant, beaucoup considéraient cette planète comme leur patrie.",
                  government : "La planet résistait aux changements de bords politiques, procurant une stabilité à travers les rebellions, la longue chute de la corrompue Ancienne République, et l'époustouflant introduction du Nouvel Ordre de l'Empereur."

         },
         {
                  name : "Mustafar",
                  asset : './assets/mustafar_zoom.dae',
                  capital : "Fralideja",
                  abstract : "Coruscant, (prononcé /'k&#596;&#633;&#601;s&#593;nt/), originellement appelée Notron, aussi connue comme le Centre Impérial ou la Reine du Noyau, était une planète située au Coeur de la Galaxie. Il était généralement accordé que Coruscant était, durant la majorité de l'histoire galactique, le monde le plus important de la galaxie. À diverses époques, il s'agissait de la capitale de la République Galactique, de l'Empire Galactique, de la Nouvelle République, de l'empire Yuuzhan Vong, de l'Alliance Galactique, brièvement de l'Empire Fel, de l'Empire Galactique de Dark Krayt, et de la Fédération Galactique du Triumvirate. En contrôlant Coruscant, ces gouvernemens contrôlaient la plupart de la galaxie.",
                  geography : " Géologiquement, la planète était composée d'un cœur fondu, entouré d'un manteau de roches et de silicate. À ses pôles se tenainet d'énormes blocs de glace populaire au près des touristes. L'entière surface de Coruscant était couverte de, gonflée par une population de plus de cent milliards à plusieurs trillions, selon l'époque. Après la fin de la Guerre des Clones, une note officielle nota 1 trilliard de résidents permanents officiels. Les statistiques n'incluaient pas les gens de passage, les travailleurs temporaires, la population non recensée, ou encore les habitants des infrastructures orbitales. À cause de ces omissions, la population réelle de Coruscant étaient estimée le triple de la note officielle.",
                  history : "L'Histoire enregistrée de Coruscant remonte à si loin qu'elle est devenue indistinguable de la légende...",
                  society : "Coruscant était le foyer d'une certaine variété d'espèces, bien que les Humaisn en représenatient la majorité. La plupart des espèces natives de la planète étaient soit exteintes soit regroupée dans les parties les plus profondes du Monde Souterrain depuis l'époque de l'Ancienne République. La planète était supposée être le foyer des Humains. Même si tous les citoyens renommés n'éaient nés à Coruscant, beaucoup considéraient cette planète comme leur patrie.",
                  government : "La planet résistait aux changements de bords politiques, procurant une stabilité à travers les rebellions, la longue chute de la corrompue Ancienne République, et l'époustouflant introduction du Nouvel Ordre de l'Empereur."
         }
]